"""Regenerate README.md for a custom PReSto LMR reconstruction.

Reads `query_params.json` and `lmr_configs.yml` from the repo root and writes
a `README.md` that surfaces the run-specific data selection and reconstruction
parameters, plus standard attribution to the LMR Template and PReSto.

The output is a pure function of the two input files — running this twice
with the same inputs produces byte-identical output, so committing the
result only creates a diff when the inputs actually change.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import yaml


TEMPLATE_REPO = "https://github.com/DaveEdge1/LMR2"
PRESTO_URL = "https://paleopresto.com"

MODE_DESCRIPTIONS = {
    "filtered": (
        "filtered (records hand-selected via PReSto's interactive map "
        "interface and queried from LiPDverse)"
    ),
    "archived": (
        "archived (a pre-built compilation pickle was downloaded directly "
        "from LiPDverse)"
    ),
    "traditional": (
        "traditional (a pre-generated proxy database pickle was downloaded "
        "from a provided URL)"
    ),
}


def _format_compilations(raw):
    """'CoralHydro2k-1_0_0,Pages2k' → 'CoralHydro2k 1.0.0, Pages2k'."""
    if not raw:
        return None
    out = []
    for token in str(raw).split(","):
        token = token.strip()
        if not token:
            continue
        if "-" in token:
            name, _, version = token.partition("-")
            out.append(f"{name.strip()} {version.replace('_', '.').strip()}")
        else:
            out.append(token)
    return ", ".join(out)


def _year_value(year):
    try:
        return int(year)
    except (TypeError, ValueError):
        return None


def _format_year(year):
    y = _year_value(year)
    if y is None:
        return str(year)
    if y < 0:
        return f"{abs(y)} BCE"
    return f"{y} CE"


def _format_period(period):
    """Render a [start, end] range, suppressing the redundant era suffix
    on the start year when both endpoints share an era."""
    if not period or len(period) < 2:
        return None
    a, b = _year_value(period[0]), _year_value(period[1])
    if a is not None and b is not None and ((a >= 0) == (b >= 0)):
        start = f"{abs(a)}" if a < 0 else f"{a}"
        return f"{start}–{_format_year(b)}"
    return f"{_format_year(period[0])}–{_format_year(period[1])}"


def _format_locrad(km):
    if km is None:
        return "—"
    try:
        return f"{int(km):,} km"
    except (TypeError, ValueError):
        return str(km)


def _format_archives(value):
    if not value:
        return None
    if isinstance(value, (list, tuple)):
        return ", ".join(str(v) for v in value if v)
    return str(value)


def build_readme(query, configs):
    mode = (query.get("mode") or "").strip().lower()
    mode_desc = MODE_DESCRIPTIONS.get(mode, mode or "—")

    compilations = _format_compilations(query.get("compilation"))
    archive_types = _format_archives(query.get("archiveTypes"))
    interp_var = query.get("interpVars") or query.get("variableName") or "temperature"

    tsids = query.get("tsids") or []
    removed_tsids = query.get("removedTsids") or []

    recon_period = _format_period(configs.get("recon_period")) or "—"
    anom_period = _format_period(configs.get("prior_anom_period")) or "—"
    nens = configs.get("nens", "—")
    seeds = configs.get("recon_seeds") or []
    assim_frac = configs.get("assim_frac", "—")
    loc_rad = _format_locrad(configs.get("recon_loc_rad"))
    months = configs.get("prior_annualize_months") or []
    annualize_label = (
        "annual mean (Jan–Dec)"
        if sorted(int(m) for m in months) == list(range(1, 13))
        else f"months {', '.join(str(m) for m in months)}"
    )

    ptype_block = configs.get("filter_proxydb_kwargs") or {}
    ptype_keys = ptype_block.get("keys") or []

    lines = []
    lines.append("# Custom LMR Reconstruction")
    lines.append("")
    lines.append(
        f"This repository was generated by [PReSto]({PRESTO_URL}) "
        "(Paleoclimate Reconstruction Storehouse) from the "
        f"[LMR Template]({TEMPLATE_REPO}). It runs a Last Millennium "
        "Reanalysis ([Tardif et al., 2019]"
        "(https://doi.org/10.5194/cp-15-1251-2019)) reconstruction over "
        "the parameters and proxy selection captured below."
    )
    lines.append("")

    lines.append("## Reconstruction parameters")
    lines.append("")
    lines.append("| Parameter | Value |")
    lines.append("|---|---|")
    lines.append(f"| Reconstruction window | {recon_period} |")
    lines.append(f"| Anomaly reference period | {anom_period} |")
    lines.append(f"| Calibration target | {interp_var} |")
    lines.append(f"| Prior averaging | {annualize_label} |")
    lines.append(f"| Ensemble size | {nens} members |")
    if not seeds:
        seeds_label = "—"
    elif len(seeds) == 1:
        seeds_label = str(seeds[0])
    else:
        seeds_label = f"{', '.join(str(s) for s in seeds)} ({len(seeds)} seeds)"
    lines.append(f"| Seeds | {seeds_label} |")
    lines.append(f"| Assimilation fraction | {assim_frac} |")
    lines.append(f"| Localization radius | {loc_rad} |")
    lines.append("")
    lines.append("(See `lmr_configs.yml` for the authoritative settings.)")
    lines.append("")

    lines.append("## Proxy data selection")
    lines.append("")
    lines.append(f"- **Mode:** {mode_desc}")
    if compilations:
        lines.append(f"- **Source compilations:** {compilations}")
    if archive_types:
        lines.append(f"- **Archive types requested:** {archive_types}")
    if ptype_keys:
        lines.append(
            "- **Proxy-type whitelist (post-load):** "
            f"{', '.join(ptype_keys)}"
        )
    if tsids:
        lines.append(f"- **Records selected:** {len(tsids)}")
    if removed_tsids:
        lines.append(f"- **Records explicitly excluded:** {len(removed_tsids)}")
    lines.append("")
    lines.append("(See `query_params.json` for the full TSID list.)")
    lines.append("")

    lines.append("## Results")
    lines.append("")
    lines.append(
        "- Reconstruction NetCDFs are committed to `recons/` after each "
        "successful run."
    )
    lines.append(
        "- A validation page (against HadCRUT5 and GISTEMP, with a proxy "
        "comparison vs PReSto2k) and the interactive visualization are "
        "deployed to GitHub Pages — see this repository's "
        "**Settings → Pages** for the deployed URL."
    )
    lines.append("")

    lines.append("## Method")
    lines.append("")
    lines.append(
        "This reconstruction reproduces the offline data-assimilation "
        "method of [Hakim et al. (2016)]"
        "(https://doi.org/10.1002/2016JD024751) using the "
        "[cfr](https://fzhu2e.github.io/cfr/) Python package "
        "([Zhu et al., 2024]"
        "(https://doi.org/10.5194/gmd-17-3409-2024)). Proxies are sourced "
        "from [LiPDverse](https://lipdverse.org)."
    )
    lines.append("")

    lines.append("## Acknowledgements")
    lines.append("")
    lines.append(
        f"Built from the [PReSto LMR Template]({TEMPLATE_REPO}) by "
        "[David Edge](https://orcid.org/0000-0001-6938-2850), "
        "[Tanaya Gondhalekar](https://orcid.org/0009-0004-2440-3266), & "
        "[Julien Emile-Geay](https://orcid.org/0000-0001-5920-4751). "
        f"Hosted by [PReSto]({PRESTO_URL})."
    )
    lines.append("")

    lines.append("---")
    lines.append(
        "*This README is regenerated automatically by "
        "`scripts/generate_readme.py` from `query_params.json` and "
        "`lmr_configs.yml`. Hand edits will be overwritten on the next run; "
        "edit the inputs (or the script) instead.*"
    )
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--query", default="query_params.json",
                        help="Path to query_params.json (default: %(default)s)")
    parser.add_argument("--configs", default="lmr_configs.yml",
                        help="Path to lmr_configs.yml (default: %(default)s)")
    parser.add_argument("--out", default="README.md",
                        help="Output README path (default: %(default)s)")
    args = parser.parse_args()

    query_path = Path(args.query)
    configs_path = Path(args.configs)

    if not query_path.exists():
        print(f"ERROR: {query_path} not found", file=sys.stderr)
        return 1
    if not configs_path.exists():
        print(f"ERROR: {configs_path} not found", file=sys.stderr)
        return 1

    with query_path.open("r", encoding="utf-8") as f:
        query = json.load(f)
    with configs_path.open("r", encoding="utf-8") as f:
        configs = yaml.safe_load(f)

    text = build_readme(query, configs)
    Path(args.out).write_text(text, encoding="utf-8")
    print(f"Wrote {args.out} ({len(text):,} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
